name: Generate GitHub Metrics # 工作流名称

on: # 触发条件
  schedule: # 定时运行
    - cron: "0 0 * * *" # 每天 UTC 00:00 运行（JST 09:00）
  workflow_dispatch: # 支持手动触发

permissions: # 设置权限
  contents: write # 允许工作流写入仓库内容

jobs:
  github-metrics: # 任务名称
    runs-on: ubuntu-latest # 运行环境
    steps:
      - uses: actions/checkout@v3 # 检出仓库代码
      - uses: lowlighter/metrics@latest # 使用 metrics Action
        with:
          token: ${{ secrets.METRICS_TOKEN }} # 使用自定义令牌
          filename: metrics.svg # 输出文件名
          base: header, activity, community, repositories # 基础统计模块
          plugin_lines: yes # 显示代码行数插件
      - name: Commit & Push # 提交生成的文件
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update GitHub metrics"
          git push
